### ISSUE TITLE
部分Android13无法授权读取缓存目录

### ISSUE THREAD

**Issue by Webpage-gh** [molihuan/BilibiliCacheVideoMerge#16]
类别：
5、无法授权

设备信息：
Android:13   App版本:1.6.9.8
机型:Xiaomi/21091116AC
设备id:
213160349c7753fe6828557da55f870c1

描述：由于安全原因，Android13的文档隐藏了data目录，无法进入目录进行授权

怎样触发bug：
打开软件，按提示授权

可能的解决方案：
对可提权至root的设备以root身份直接读写任意文件
借助shareuid或mt的注入文件提供器暴露缓存目录
使用存储重定向类软件如存储空间隔离、Cleaner重定向缓存目录到公共文件夹（用户可操作）
不太可能的方案：
提权至shell进行读取，会报错Permission denied

**Comment by molihuan** [comment]
> 类别：
> 5、无法授权
> 
> 设备信息：
> Android:13   App版本:1.6.9.8
> 机型:Xiaomi/21091116AC
> 设备id:
> 213160349c7753fe6828557da55f870c1
> 
> 描述：由于安全原因，Android13的文档隐藏了data目录，无法进入目录进行授权
> 
> 怎样触发bug：
> 打开软件，按提示授权
> 
> 可能的解决方案：
> 对可提权至root的设备以root身份直接读写任意文件
> 借助shareuid或mt的注入文件提供器暴露缓存目录
> 使用存储重定向类软件如存储空间隔离、Cleaner重定向缓存目录到公共文件夹（用户可操作）
> 不太可能的方案：
> 提权至shell进行读取，会报错Permission denied

确实，有的安卓13可以授权正常使用，有的不能授权，还有的授权了，也无法操作文件

**Comment by Webpage-gh** [comment]
这个问题的原因找到了，是因为高于14-10484568(340818020)版本的文件(com.google.android.documentsui)会隐藏Android/data目录，导致无法浏览和授权。卸载文件到出厂版本就可能解决这个问题
